version: '3'

networks:
  static-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24

services:
    web:
        build: .
        ports:
            - "8000:8080"
        networks:
          static-network:
            ipv4_address: 192.168.0.5
        links:
            - database
        volumes:
            - .:/app
    database:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'portal'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'portal'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./portalDBPopulator.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - 3306:3306
        networks:
          static-network:
            ipv4_address: 192.168.0.55

    ldap:
        image: osixia/openldap:1.5.0
        volumes:
            - ./NebulaeLDAPPopulator.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif
            - ldapdata_var:/var/lib/ldap
            - ldapdata_etc:/etc/ldap/slapd.d
        command: [--copy-service,  --loglevel, debug]
        environment:
            LDAP_ORGANISATION: 'Nebulae'
            LDAP_DOMAIN: 'nebulae.co'
            LDAP_READONLY_USER: 'true'
            LDAP_BASE_DN: 'dc=nebulae,dc=co'
            LDAP_TLS: 'false'
        networks:
          static-network:
            ipv4_address: 192.168.0.58

volumes:
    mysqldata: {}
    ldapdata_var: {}
    ldapdata_etc: {}


